
name: Build and deploy coursework_5
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker buildx build --platform linux/amd64 -t vladimirbodrin/coursework_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push vladimirbodrin/coursework_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@2
      - name: render data
        run: |
          mkdir flask_project
          cat docker-compose-ci.yaml | envsubst > flask_project/docker-compose.yaml
          cd flask_project
          mkdir data
          cat data/equipment.json | envsubst > flask_project/data/equipment.json
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "flask_project/docker-compose.yaml, flask_project/data/equipment.json"
          target: "coursework_5"
          strip_components: 1



