
name: Build and deploy coursework_5
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker buildx build --platform linux/amd64 -t vladimirbodrin/coursework_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push vladimirbodrin/coursework_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy_file:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render data
        run: |
          mkdir flask_project
          cat docker-compose-ci.yaml | envsubst > flask_project/docker-compose.yaml
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "flask_project/docker-compose.yaml"
          target: "coursework_5"
          strip_components: 1
      - name: deploy_app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd coursework_5
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d
            
            



